version: "3.9"
services:
  tfg-mysql:
    image: mysql:8.0
    container_name: tfg-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: inmobiliaria
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/inmobiliaria_dump.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - tfg-network

  tfg-backend:
    build: ./backend
    container_name: tfg-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://tfg-mysql:3306/inmobiliaria
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: devpass
    depends_on:
      tfg-mysql:
        condition: service_healthy
    networks:
      - tfg-network

networks:
  tfg-network:
    driver: bridge

volumes:
  mysql-data: